import { COLORS } from "@/constants/colors";
import { Dimensions, Platform, StyleSheet } from "react-native";
const { height, width } = Dimensions.get("window");

export const componentStyle = StyleSheet.create({
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: height*0.03,
    paddingHorizontal: 15,
    height: height * 0.06,
    width: "90%",
    marginVertical: height * 0.01,
    borderWidth: height * 0.005,
    borderColor: COLORS.red
  },
  inputIcon: {
    width: "6%",
    height: "50%",
    marginRight: 10,
    tintColor: "COLORS.textMuted",
  },
  inputText: {
    flex: 1,
    fontSize: height * 0.016,
    color: COLORS.textMuted,
    fontFamily: "Poppins-SemiBold",
  },
    iconPerfilContainer: {
    height: height * 0.15,
    width: height * 0.15,
    borderRadius: (height * 0.15) / 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
    position: "relative",
    borderWidth: 4,
    borderColor: COLORS.red,
  },
  iconPerfilImage: {
    height: "100%",
    width: "100%",
    borderRadius: (height * 0.15) / 2,
    resizeMode: "cover",
  },
  popUpButtonContainer: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  gap: 70,
  marginTop: 12,
  width: "100%",
},
  editButtonContainer: {
    position: "absolute",
    bottom: 0,
    right: -height * 0.15 * 0.1,
    height: height * 0.15 * 0.35,
    width: height * 0.15 * 0.35,
    backgroundColor: COLORS.black,
    borderRadius: "100%",
    borderWidth: height * 0.004,
    borderColor: COLORS.gold,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  editButtonIcon: {
    width: "90%",
    height: "90%",
    resizeMode: "contain",
    tintColor: COLORS.gold,
  },
   titleBarContainer: {
      width: '100%',
      height: height * 0.12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: COLORS.primary,
      marginTop: 0,
      marginBottom: height * 0.03,
      boxShadow: "0px 4px 40px 10px rgba(0, 0, 0, 0.20)",
      shadowColor: COLORS.black,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 10,
  },
  titleBackground: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: -1,
  },
  welcomeTitle: {
      fontSize: height * 0.035,
      fontFamily: 'Poppins-SemiBold',
      color: COLORS.gold,
      textAlign: 'center',
      zIndex: 1,
      paddingTop: 10,
  },
    codeInputContainer: {
    flexDirection: "row",
    gap: height * 0.012,
    justifyContent: "center",
    marginVertical: height * 0.012,
    width: "100%",
  },
  codeInputBox: {
    width: width * 0.09,
    height: width * 0.11,
    maxWidth:height * 0.08,
    maxHeight: height * 0.1,
    backgroundColor: COLORS.primaryDark,
    borderRadius: 10,
    color: COLORS.gold,
    marginTop: height * 0.01,
    fontSize: height * 0.03,
    textAlign: "center",
    fontFamily: "Poppins-SemiBold",
  },
  box: {
    backgroundColor: COLORS.primary,
    borderRadius: 30,
    alignSelf: "center",
    boxShadow: "0px 4px 40px 40px rgba(0, 0, 0, 0.2)",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 15.8,
    elevation: 16,
    overflow: "visible",
  },
  boxDark: {
    backgroundColor: COLORS.primaryDark,
    borderColor: COLORS.red,
    borderWidth: height * 0.007,
    borderRadius: 30,
    alignSelf: "center",
    overflow: "visible",
    padding: height * 0.03,
  },
  popupOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)"
  },
  popup: {
    width: "84%",
    padding: 24,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    borderColor: COLORS.red,
    borderWidth: height * 0.007,
    alignItems: "center",
  },
  popupText: {
    color: COLORS.textMuted,
    fontSize: height * 0.018,
    fontFamily: "Poppins-SemiBold",
    textAlign: "center",
  },
  exclamationIcon: {
    width: height * 0.05,
    height: height * 0.05,
    marginBottom: height * 0.02,
    alignItems: "center",
  },
  couponContainer: {
    width: width * 0.75,
    marginVertical: height * 0.02,
    borderRadius: height * 0.025,
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  couponBox: {
    backgroundColor: COLORS.gold,
    borderRadius: height * 0.02,
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.02,
    minHeight: height * 0.10,
    justifyContent: 'center',
  },
  coupomContentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  coupomTextContainer: {
    flex: 1,
    justifyContent: 'center',
    marginRight: width * 0.05,
  },
  coupomTitles: {
    fontSize: height * 0.030,
    paddingBottom: height * 0.004,
    fontWeight: '900',
    color: COLORS.black,
    fontFamily: 'Poppins-SemiBold',
  },
  coupomSubtitle: {
    fontSize: height * 0.013,
    color: COLORS.black,
    fontFamily: 'Poppins-Regular',
    lineHeight: height * 0.02,
  },
  coupomIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  coupomIcon: {
    width: height * 0.08,
    height: height * 0.08,
  },
    userPipokaContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.primaryDark,
    borderRadius: height,
    width: "55%",
    marginBottom: height * 0.005,
    position: "relative",
  },
  UserPipokaTextWrapper: {
    flex: 1,
  },
  userPipokaBaseText: {
    fontSize: height * 0.012,
    color: COLORS.white,
    fontFamily: "Poppins-Regular",
    textAlign: "center",
  },
  userPipokaCount: {
    fontSize: height * 0.024,
    fontFamily: "Poppins-SemiBold",
  },
  userPipokaIconWrapper: {
    width: height * 0.06,
    height: height * 0.06,
    borderRadius: height * 0.03,
    borderColor: COLORS.primaryDark,
    borderWidth: height * 0.005,
    position: "absolute",
    backgroundColor: COLORS.gold,
    alignItems: "center",
    right: -5,
    justifyContent: "center",
  },
  userPipokaIcon: {
    width: "70%",
    height: "70%",
  },
  coupomContainer: {
    alignItems: "center",
    paddingHorizontal: 8,
  },
  coupomTitle: {
    color: COLORS.gold,
    fontSize: height * 0.02,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 16,
  },
  coupomGlowContainer: {
    shadowColor: COLORS.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    borderRadius: height * 0.15 / 2,
    elevation: 20,
    marginBottom: 4,
  },
  coupomCircle: {
    width: height * 0.13,
    height: height * 0.13,
    borderRadius: height * 0.15 / 2,
    backgroundColor: COLORS.gold,
    justifyContent: "center",
    alignItems: "center",
  },
  coupomCircleValue: {
    fontSize: height * 0.065,
    fontWeight: "900",
    color: "COLORS.black",
    textAlign: "center",
    includeFontPadding: false,
  },
  coupomCircleCurrency: {
    fontSize: 18,
    fontWeight: "bold",
    textAlignVertical: "top",
  },
  coupomPipokaText: {
    color: COLORS.gold,
    fontSize: height * 0.01,
    fontFamily: "Poppins-SemiBold",
  },
  coupomPipokaCost: {
    fontFamily: "Poppins-SemiBold",
    color: COLORS.gold,
    fontSize: height * 0.024,
  },
  coupomDivider: {
    width: "100%",
    height: 4,
    backgroundColor: COLORS.red,
    borderRadius: 2,
    marginVertical: 2,
  },
  coupomDescription: {
    color: COLORS.gold,
    fontSize: height * 0.011,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 1,
  },

  userCouponContainer: {
    position: "relative",
    marginVertical: height * 0.02,
    width: "90%",
    alignSelf: "center",
  },
  userCouponTicketWrapper: {
    flexDirection: "row",
    backgroundColor: COLORS.primaryDark,
    borderRadius: 20,
    borderWidth: height * 0.007,
    borderColor: COLORS.red,
    overflow: "hidden",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 1,
  },
  userCouponCutoutLeft: {
    position: "absolute",
    left: -(height * 0.036), 
    top: "50%",
    marginTop: -(height * 0.04),
    width: height * 0.08,
    height: height * 0.08,
    backgroundColor: COLORS.background,
    transform: [{ rotate: "45deg" }],
    borderTopWidth: height * 0.007,
    borderRightWidth: height * 0.007,
    borderColor: COLORS.red,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 2,
    borderTopLeftRadius: 2, 
    zIndex: 10,
  },
  userCouponCutoutRight: {
    position: "absolute",
    right: -(height * 0.036), 
    top: "50%",
    marginTop: -(height * 0.04),
    width: height * 0.08,
    height: height * 0.08,
    backgroundColor: COLORS.background,
    transform: [{ rotate: "45deg" }],
    borderBottomWidth: height * 0.007,
    borderLeftWidth: height * 0.007,
    borderColor: COLORS.red,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 2,
    borderTopLeftRadius: 2,
    zIndex: 10,
  },
  userCouponLeftSection: {
    flex: 1.1, 
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.03,
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 2,
    borderRightColor: COLORS.red,
  },
  userCouponLeftTitle: {
    fontSize: height * 0.022,
    fontWeight: "bold",
    color: COLORS.gold,
    textAlign: "center",
    marginBottom: height * 0.02,
    lineHeight: height * 0.028,
    fontFamily: "Poppins-Bold",
  },
  userCouponCircleGlow: {
    width: height * 0.13,
    height: height * 0.13,
    borderRadius: height * 0.065,
    backgroundColor: COLORS.gold,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: height * 0.02,
    shadowColor: COLORS.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 15,
  },
  userCouponCircleText: {
    fontSize: height * 0.055,
    fontWeight: "900",
    color: COLORS.primaryDark,
    includeFontPadding: false,
  },
  coupomCircleCurrency: { 
    fontSize: height * 0.025,
    color: COLORS.primaryDark,
    fontWeight: "bold",
  },
  userCouponLeftDescription: {
    fontSize: height * 0.012,
    color: COLORS.gold,
    textAlign: "center",
    fontStyle: "italic",
    fontFamily: "Poppins-Regular",
  },
  userCouponRightSection: {
    flex: 1,
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.03,
    justifyContent: "space-between",
    alignItems: "center", 
  },
  userCouponRightTitle: {
    fontSize: height * 0.024,
    fontWeight: "bold",
    color: COLORS.gold,
    marginBottom: height * 0.03,
    fontFamily: "Poppins-Bold",
    textAlign: "center",
  },
  userCouponDetailRow: {
    flexDirection: "row", 
    alignItems: "center", 
    marginBottom: height * 0.01,
  },
  userCouponDetailLabel: {
    fontSize: height * 0.017,
    fontWeight: "600",
    color: COLORS.gold,
    fontFamily: "Poppins-SemiBold",
    marginRight: 4, 
  },
  userCouponDetailValue: {
    fontSize: height * 0.017,
    color: COLORS.gold, 
    fontFamily: "Poppins-Regular",
  },
  userCouponStatusActive: {
    fontSize: height * 0.017,
    fontWeight: "600",
    color: COLORS.gold, 
    fontFamily: "Poppins-SemiBold",
  },
  userCouponStatusInactive: {
    fontSize: height * 0.017,
    fontWeight: "600",
    color: COLORS.red,
    fontFamily: "Poppins-SemiBold",
  },
  dropdownContainer: {
    backgroundColor: COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: height * 0.02,
    paddingVertical: height * 0.007,
    borderRadius: height * 0.012,
    gap: height * 0.008,
  },
  dropdownText: {
    color: COLORS.red,
    fontFamily: 'Poppins-SemiBold',
    fontSize: height * 0.021,
  },
badgeWrapper: {
    position: 'absolute',
    top: -(height * 0.018), 
    left: 0,
    right: 0,
    justifyContent: 'center',
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgePill: {
    backgroundColor: COLORS.red,
    borderColor: COLORS.gold,
    borderWidth: height * 0.003,
    borderRadius: height * 0.025,
    paddingVertical: height * 0.005,
    paddingHorizontal: height * 0.015,
    marginRight: -(height * 0.018),
    paddingRight: height * 0.025,
  },
  badgeText: {
    color: COLORS.white,
    fontFamily: 'Poppins-Bold',
    fontSize: height * 0.012, 
  },
  badgeCircle: {
    width: height * 0.04,
    height: height * 0.04,
    borderRadius: (height * 0.04) / 2,
    backgroundColor: COLORS.red,
    borderColor: COLORS.gold,
    borderWidth: height * 0.003,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2, 
  },
});

export const synopsisStyle = StyleSheet.create({
  container: {
    backgroundColor: '#D9D9D9',
    borderRadius: 16,
    padding: 15,
    marginTop: 20,
  },
  label: {
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    marginBottom: 10,
    fontSize: 16,
  },
  input: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    textAlignVertical: 'top',
    minHeight: 120,
    fontSize: 14,
  },
});
