import { Dimensions, Platform, StyleSheet } from "react-native";
const { height, width } = Dimensions.get("window");
import { COLORS } from "@/constants/colors";

export const movieStyle = StyleSheet.create({
  filmesContainer: {
    flex: 1,
    backgroundColor: "#B22300",
  },
  filmesHeader: {
    paddingHorizontal: "5%",
    paddingTop: height * 0.02,
    alignItems: "center",
  },
  filmesLogo: {
    width: height * 0.2,
    height: height * 0.08,
    resizeMode: "contain",
    marginBottom: height * 0.02,
  },

  filmesListContent: {
    paddingHorizontal: "4%",
    paddingBottom: height * 0.22,
  },
  filmesRow: {
    justifyContent: "space-between",
  },
  filmesCard: {
    backgroundColor: "#2A0800",
    width: "48%",
    borderRadius: height * 0.02,
    padding: "2%",
    marginVertical: height * 0.012,
    borderWidth: 4,
    borderColor: "#FE481B",
    alignItems: "center",
  },
  filmesPoster: {
    width: "100%",
    height: height * 0.25,
    borderRadius: height * 0.015,
  },
  filmesMovieTitle: {
    color: "#FFFEB2",
    fontSize: height * 0.015,
    fontWeight: "bold",
    marginTop: height * 0.01,
    textAlign: "center",
  },
  filmesRatingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: height * 0.006,
  },
  filmesRatingLabel: {
    color: "#FFFEB2",
    fontSize: height * 0.011,
    fontWeight: "bold",
  },
  filmesTagRow: {
    flexDirection: "row",
    gap: 5,
    marginBottom: height * 0.012,
  },
  filmesTagYellow: {
    backgroundColor: "#FFFEB2",
    borderRadius: height * 0.02,
    paddingHorizontal: "4%",
    paddingVertical: "1%",
  },
  filmesTagRed: {
    backgroundColor: "#B22300",
    borderRadius: height * 0.02,
    paddingHorizontal: "4%",
    paddingVertical: "1%",
  },
  filmesTagText: {
    fontSize: height * 0.01,
    fontWeight: "bold",
    color: "#000",
  },
  filmesDetailsButton: {
    backgroundColor: "#B22300",
    width: "60%",
    paddingVertical: height * 0.01,
    borderRadius: height * 0.015,
  },
  filmesSearchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginVertical: height * 0.015,
  },
  filmesInputWrapper: {
    flex: 1,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  filmesDetailsButtonText: {
    color: "#FFFEB2",
    textAlign: "center",
    fontSize: height * 0.014,
    fontWeight: "bold",
  },
  filmesFooterBtn: {
    alignItems: "center",
    marginVertical: height * 0.025,
  },
  filmesStarsWrapper: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 3,
    gap: 1,
  },
  filmesSingleStarContainer: {
    position: "relative",
  },
  filmesStarBackground: {
    color: "#4A2010",
    fontSize: height * 0.014,
  },
  filmesStarOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    overflow: "hidden",
  },
  filmesStarForeground: {
    color: "#FFFEB2",
    fontSize: height * 0.014,
  },

  detailsMainContainer: {
    flex: 1,
    backgroundColor: '#8E1600',
  },
  detailsHeaderPill: {
    backgroundColor: '#B22300', 
    width: width * 0.8,
    paddingVertical: height * 0.015,
    borderRadius: 50,
    alignSelf: 'center',
    marginTop: height * 0.02,
    marginBottom: height * 0.03,
    borderWidth: 2,
    borderColor: "#FE481B",
    zIndex: 100, 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
  },
  detailsTitleText: {
    color: "#FFFEB2",
    fontSize: height * 0.022,
    fontWeight: "bold",
    textAlign: "center",
  },
  detailsTopBar: {
    backgroundColor: '#B22300', 
    width: '100%',
    paddingVertical: height * 0.025,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20, 
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 8,
  },
  detailsBackgroundImage: {
    position: 'absolute', 
    top: 0,
    left: 0,
    right: 0,
    height: height * 0.40, 
    opacity: 0.9,
    zIndex: 0, 
  },
  detailsScrollContent: {
    paddingBottom: 120, 
    paddingTop: 25,
  },
  detailsPosterWrapper: {
    alignItems: 'center', 
    zIndex: 10,
  },
  detailsPoster: {
    width: width * 0.45,  
    height: height * 0.3, 
    borderRadius: 15,    
    alignSelf: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 15,
  },
  detailsContentWrapper: {
    flex: 1,
    marginTop: -height * 0.05, 
    backgroundColor: '#8E1600', 
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 10, 
    zIndex: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  detailsRatingCard: {
    backgroundColor: "#B22300",
    paddingHorizontal: width * 0.06, 
    paddingVertical: height * 0.01,
    borderRadius: 30, 
    alignSelf: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: "#FFFEB2",
    marginTop: height * 0.060, 
    marginBottom: height * 0.02, 
    zIndex: 15,
  },
  detailsInfoGroup: {
    gap: 5, 
    paddingBottom: 15,
  },
  detailsWatchlistBtnWrapper: {
    width: width * 0.55, 
    alignSelf: 'center',
    marginTop: height * 0.02, 
    marginVertical: height * 0.01,
  },
  detailsSynopsisCard: {
    backgroundColor: "#FFF",
    width: width * 0.9, 
    alignSelf: 'center', 
    paddingHorizontal: width * 0.05, 
    paddingVertical: width * 0.04, 
    borderRadius: height * 0.02,
    marginVertical: height * 0.02,
  },
  detailsSynopsisText: {
    lineHeight: 22, 
    color: "#000",
    textAlign: 'left', 
    fontSize: height * 0.018,
  },
  detailsSectionGrey: {
    backgroundColor: "#D9D9D9", 
    width: width * 0.9, 
    alignSelf: 'center',
    padding: width * 0.05,
    borderRadius: height * 0.03, 
    marginVertical: height * 0.015,
  },
  detailsStarsContainer: {
    flexDirection: 'row', 
    justifyContent: 'center', 
    marginBottom: 15,
  },
  detailsInfoRow: {
    backgroundColor: "#2A0800",
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: width * 0.04,
    paddingHorizontal: width * 0.05,
    borderRadius: height * 0.04, 
    marginBottom: height * 0.01,
    width: width * 0.9, 
    alignSelf: 'center', 
  },
  detailsInfoText: {
    color: "#FFFEB2",
    marginLeft: width * 0.03,
    fontWeight: "bold",
    fontSize: height * 0.016,
    flex: 1, 
  },
  detailsReviewInput: {
    backgroundColor: "#FFF",
    borderRadius: height * 0.015,
    padding: width * 0.04,
    height: height * 0.12,
    textAlignVertical: 'top',
    marginBottom: height * 0.015,
    width: '100%', 
  },
  detailsButtonWrapper: {
    alignItems: 'center',
  },
  detailsReviewItem: {
    backgroundColor: "#FFF",
    padding: width * 0.04,
    borderRadius: height * 0.015,
    marginBottom: height * 0.01,
    flexDirection: 'row',
    alignItems: 'center', 
    width: '100%', 
  },
  detailsReviewAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFEB2',
    marginRight: width * 0.04,
    borderWidth: 2,
    borderColor: '#2A0800',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailsReviewContent: {
    flex: 1, 
  },
  detailsViewMoreWrapper: {
    marginTop: 10,
  },
});